# Generated by Django 2.0.6 on 2021-04-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselesson',
            name='lesson_video',
            field=models.FileField(blank=True, null=True, upload_to='video', verbose_name='视频'),
        ),
    ]
